# Generated by Django 4.2 on 2023-04-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionDjango', '0002_profesor_cursos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='camada',
            new_name='comision',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='cursos',
        ),
    ]
